// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  content_section: dynamic(() => import("./ContentSection")),
  footer_link: dynamic(() => import("./FooterLink")),
  fullpage_text: dynamic(() => import("./FullpageText")),
  hero_section: dynamic(() => import("./HeroSection")),
  kontakformular: dynamic(() => import("./Kontaktformular")),
  link: dynamic(() => import("./Navigationslinks")),
  modal: dynamic(() => import("./Modal")),
};
