// Only export the things that are actually needed, cut out everything else
export { WebGLRenderer } from "three/src/renderers/WebGLRenderer.js";
export { ShaderLib } from "three/src/renderers/shaders/ShaderLib.js";
export { UniformsLib } from "three/src/renderers/shaders/UniformsLib.js";
export { UniformsUtils } from "three/src/renderers/shaders/UniformsUtils.js";
export { ShaderChunk } from "three/src/renderers/shaders/ShaderChunk.js";
export { Scene } from "three/src/scenes/Scene.js";
export { Mesh } from "three/src/objects/Mesh.js";
export { LineSegments } from "three/src/objects/LineSegments.js";
export { Line } from "three/src/objects/Line.js";
export { CanvasTexture } from "three/src/textures/CanvasTexture.js";
export { Group } from "three/src/objects/Group.js";
export { CylinderGeometry } from "three/src/geometries/CylinderGeometry.js";
export { Float32BufferAttribute } from "three/src/core/BufferAttribute.js";
export { SphereGeometry } from "three/src/geometries/SphereGeometry.js";
export { PlaneGeometry } from "three/src/geometries/PlaneGeometry.js";
export { BoxGeometry } from "three/src/geometries/BoxGeometry.js";

export { EdgesGeometry } from "three/src/geometries/EdgesGeometry.js";
export { Material } from "three/src/materials/Material.js";
export { MeshBasicMaterial } from "three/src/materials/MeshBasicMaterial.js";
export { LineDashedMaterial } from "three/src/materials/LineDashedMaterial.js";
export { SpriteMaterial } from "three/src/materials/SpriteMaterial.js";
export { LineBasicMaterial } from "three/src/materials/LineBasicMaterial.js";
export { TextureLoader } from "three/src/loaders/TextureLoader.js";
export { Texture } from "three/src/textures/Texture.js";
export { SpotLightShadow } from "three/src/lights/SpotLightShadow.js";
export { SpotLight } from "three/src/lights/SpotLight.js";
export { PointLight } from "three/src/lights/PointLight.js";
export { DirectionalLight } from "three/src/lights/DirectionalLight.js";
export { AmbientLight } from "three/src/lights/AmbientLight.js";
export { PerspectiveCamera } from "three/src/cameras/PerspectiveCamera.js";
export { BufferGeometry } from "three/src/core/BufferGeometry.js";
export * from "three/src/core/BufferAttribute.js";
export { Object3D } from "three/src/core/Object3D.js";
export { Vector4 } from "three/src/math/Vector4.js";
export { Matrix4 } from "three/src/math/Matrix4.js";
export { Vector3 } from "three/src/math/Vector3.js";
export { Vector2 } from "three/src/math/Vector2.js";
export { Quaternion } from "three/src/math/Quaternion.js";
export { Color } from "three/src/math/Color.js";
export * from "three/src/math/MathUtils.js";
export * from "three/src/constants.js";
export { InstancedBufferGeometry } from "three/src/core/InstancedBufferGeometry.js";
export { InstancedMesh } from "three/src/objects/InstancedMesh.js";
export { InstancedInterleavedBuffer } from "three/src/core/InstancedInterleavedBuffer.js";
export { Euler } from "three/src/math/Euler.js";
